### ISSUE TITLE
Multi-version Flux documentation

### ISSUE THREAD

**Issue by makkes** [fluxcd/website#1534]
As part of our [long-term support pledge](https://github.com/fluxcd/flux2/pull/3254) going into effect with Flux 2.0.0 we need to make the Flux docs available for all supported versions (and likely older versions as well).

## TODOs

- [x] *.fluxcd.io sub-domains
- [x] Netlify automation for different versions based on branch
- [x] #1577 
- [x] #1592 
- [x] Drop-down for each minor version: https://www.docsy.dev/docs/adding-content/versioning/#adding-a-version-drop-down-menu
- [x] show warning on the sub-domain pages, similar to the [one shown on the K8s docs](https://v1-26.docs.kubernetes.io/).
- [ ] Document new release and development process for docs

**Comment by stefanprodan** [comment]
Why are we blocking 2.0.0? I see this as a requirement for 2.1.0 which is some months away.

**Comment by makkes** [comment]
As discussed [on Slack (private channel)](https://cloud-native.slack.com/archives/C02JQ9GLP26/p1687945789986839) we will hold this until after 2.0.0 because there's more pressing concerns right now.
