### ISSUE TITLE
Todo items post legacy docs import

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#327]
- [x] update all links within f/website: https://github.com/fluxcd/website/pull/330
- [x] merge https://github.com/fluxcd/helm-operator/pull/610
- [x] Figure out redirects for flux
- [x] Figure out redirects for helm-operator
- [x] Remove https://github.com/fluxcd/website/blob/main/layouts/docs/baseof.html#L5-L7
- [x] Remove docs from flux repo: https://github.com/fluxcd/flux/pull/3491
- [x] Remove docs from helm-op repo: https://github.com/fluxcd/helm-operator/pull/611
- [x] remove `test-flux` and `test-helm-op` projects from rtfd
- [ ] Look into Algolia search for legacy docs: https://docsearch.algolia.com/docs/config-file/#using-custom-tags
- [ ] update https://fluxcd.io/legacy landing page - add more text to it (@kingdonb)
