### ISSUE TITLE
GA roadmap: Cloud specific guides (AWS, Azure, Google Cloud, more?)

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#856]
From <https://fluxcd.io/roadmap/>

Let's discuss "Cloud specific guides (AWS, Azure, Google Cloud, more?)" - what do we want to add to our docs to be able to resolve this issue?

- [x] AWS
  - [x] [CodeCommit](https://fluxcd.io/docs/use-cases/aws-codecommit/)
  - [x] [Elastic Container Registry](https://fluxcd.io/docs/use-cases/aws-codecommit/#image-updates-with-elastic-container-registry)
      - [x] [Using Native AWS ECR Auto-Login](https://fluxcd.io/docs/guides/image-update/#using-native-aws-ecr-auto-login)
  - [x] [Bucket](https://fluxcd.io/docs/components/source/buckets/#aws)
  - [x] [Secret decryption with KMS](https://fluxcd.io/docs/use-cases/aws-codecommit/#secrets-management-with-sops-and-aws-kms)
- [x] Azure
  - [x] [DevOps Repositories](https://fluxcd.io/docs/use-cases/azure/#flux-installation-for-azure-devops)
  - [x] Container Registry
    - [x] [For Helm Repositories](https://fluxcd.io/docs/use-cases/azure/#helm-repositories-on-azure-container-registry)
    - [x] [For Image Updates](https://fluxcd.io/docs/use-cases/azure/#image-updates-with-azure-container-registry)
      - [x] [Using Native Azure ACR Auto-Login](https://fluxcd.io/docs/guides/image-update/#using-native-azure-acr-auto-login)
  - [x] Storage
    - [x] [Service Principal Secret](https://fluxcd.io/docs/components/source/buckets/#azure-service-principal-secret-example)
    - [x] [Service Principal Certificate](https://fluxcd.io/docs/components/source/buckets/#azure-service-principal-certificate-example)
    - [x] [Managed Identity with the AZURE_CLIENT_ID](https://fluxcd.io/docs/components/source/buckets/#azure-managed-identity-with-client-id-example)
    - [x] [Blob Shared Key](https://fluxcd.io/docs/components/source/buckets/#azure-blob-shared-key-example)
    - [x] Managed Identity with a system-assigned identity (https://github.com/fluxcd/website/issues/961)
    - [x] Shared Access Signature (SAS) (depends on implementation https://github.com/fluxcd/source-controller/pull/738)
  - [x] [Secret decryption with KeyVault](https://fluxcd.io/docs/use-cases/azure/#secrets-management-with-sops-and-azure-key-vault)
  - [x] [Event Hub with Notification Controller](https://fluxcd.io/docs/use-cases/azure/#azure-event-hub-with-notification-controller)
- [x] Google Cloud
  - [x] Source Repository (https://github.com/fluxcd/website/issues/962)
  - [x] Container Registry
    - [x] [For Image Updates](https://fluxcd.io/docs/guides/cron-job-image-auth/#gcp-container-registry)
      - [x] [Using Native GCP GCR Auto-login](https://fluxcd.io/docs/guides/image-update/#using-native-gcp-gcr-auto-login)
  - [x] Storage
    - [x] [Workload Identity](https://fluxcd.io/docs/components/source/buckets/#gcp-example)
    - [x] [Static Auth](https://fluxcd.io/docs/components/source/buckets/#gcp-static-auth-example)
  - [x] [Secret decryption with KMS](https://fluxcd.io/docs/guides/mozilla-sops/#google-cloud)

**Comment by pjbgf** [comment]
Removed Workload Identity, which will be tracked separately with a post-GA target.
